### ISSUE TITLE
Suggested Improvements 

### ISSUE THREAD

**Issue by bloblems** [lpg0/plaid-transaction-script#2]
Hello, I wanted to ask if I could make a Pull Request on this project as I was able to improve upon it and add some features that would be of use to people making basic financial spreadsheets.

- I added a way for it to write to a specific sheet by name instead of just the active sheet
- I added a get Current Balance sheet
- I added a way for it to remove duplicates and sort the row
- I added a way for it to dump all the data at once instead of row by row
- I added a category column
- I redid the Start and End date function to remove an error that happened when the month was 12

**Comment by lpg0** [comment]
Absolutely! I'm glad you were able to improve on it.
